version: '3.8'

services:
  admin-portal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./public/images:/app/public/images
    environment:
      - NODE_ENV=production
      - PORT=9000
      # Use the PostgREST service name from the network inspection
      - POSTGREST_URL=http://postgrest-postgrest-1:3000
    networks:
      - postgrest_default
    restart: unless-stopped

networks:
  postgrest_default:
    external: true

