version: '3.8'

services:
  admin-portal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./public/images:/app/public/images
    environment:
      - NODE_ENV=production
      - PORT=9000
    restart: unless-stopped